Repository FewOldTunes/Eldermoor, pull requests merged in 2025-03, with the labels that each got.

#15 Renames Cephas to Lythius, and adds boon descriptions for saints
  _maps/map_files/matthios_tomb/fightpit.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/templates/malums_anvil_dungeons/embercradle.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/vanderlin/vanderlin_highpop.dmm
  code/__DEFINES/roguetown.dm
  code/datums/gods/faiths/veneration.dm
  code/datums/gods/patrons/forgotten.dm
  code/datums/gods/patrons/veneration.dm
  code/datums/migrants/waves/heartfell_wave.dm
  code/modules/admin/admin.dm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
  code/modules/spells/roguetown/acolyte/general.dm
Labels: mapping

#19 Quick Fixes
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/vanderlin/vanderlin_highpop.dmm
  code/datums/gods/patrons/forgotten.dm
  code/game/objects/items/rogueitems/books.dm
  code/game/objects/structures/decorations/astratanshard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/preacher.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
  stonekeep.dme
  strings/rt/Lore_Primer.json
Labels: mapping

#20 Gives Human skin tones languages. Fixes areas. Re-does some feldsher gear. Re-writes the Ten to be Saints in all mentions
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/vanderlin/vanderlin_highpop.dmm
  code/controllers/subsystem/rogue/devotion.dm
  code/datums/gods/faiths/inhumen_pantheon.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/datums/gods/patrons/veneration.dm
  code/datums/migrants/waves/crusader_wave.dm
  code/datums/migrants/waves/follower_of_the_tens.dm
  code/datums/stress/negative_events.dm
  code/game/area/roguetownareas.dm
  code/game/objects/structures/fluff.dm
  code/modules/antagonists/roguetown/villain/zizocult.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/events/rogue/_rogue.dm
  code/modules/jobs/job_types/roguetown/church/inquisitor.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/nobility/feldsher.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
  code/modules/mob/living/death.dm
  code/modules/roguetown/roguejobs/fisher/leeches.dm
  code/modules/spells/roguetown/acolyte/general.dm
  code/modules/spells/roguetown/orison_touch.dm
  strings/laws_of_the_land.json
  strings/phobia.json
  strings/rt/Lore_Primer.json
Labels: mapping

#21 Minor Toll Guard update. Moves doctors office from third floor to second floor of manor
  _maps/map_files/vanderlin/otherz/vanderlin_bog.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/vanderlin/vanderlin_highpop.dmm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/game/objects/structures/mineral_doors.dm
  code/modules/jobs/job_types/roguetown/garrison/tollguard.dm
  code/modules/jobs/job_types/roguetown/garrison/tollkeeper.dm
  strings/rt/Lore_Primer.json
Labels: mapping

#25 Slight map change
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: mapping

#28 Re-adds Green Jester as alt skin
  _maps/map_files/vanderlin/vanderlin.dmm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/peasants/jester.dm
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/shirts.dmi
  stonekeep.dme
Labels: mapping

#30 MORE BOG CHANGES AND ADDS BATTLE NUN ROLE
  .github/ISSUE_TEMPLATE/config.yml
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/vanderlin/vanderlin_highpop.dmm
  code/__HELPERS/roundend.dm
  code/datums/migrants/migrant_wave.dm
  code/datums/migrants/waves/grenzelhoft_wave.dm
  code/datums/migrants/waves/heartfell_wave.dm
  code/datums/migrants/waves/prisoner_wave.dm
  code/datums/migrants/waves/returning_bannermen.dm
  code/datums/migrants/waves/rockhill_wave.dm
  code/datums/migrants/waves/zybantine_wave.dm
  code/game/gamemodes/objectives_rogue.dm
  code/game/objects/structures/fluff.dm
  code/modules/antagonists/roguetown/roleobjs/purishep.dm
  code/modules/antagonists/roguetown/villain/aspirant.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/battlenun.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/noble.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lchef.dm
  code/modules/jobs/job_types/roguetown/church/adept.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/garrison/mayor.dm
  code/modules/jobs/job_types/roguetown/nobility/archivist.dm
  code/modules/jobs/job_types/roguetown/nobility/consort.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/nobility/minor_noble.dm
  code/modules/jobs/job_types/roguetown/peasants/cook.dm
  code/modules/jobs/job_types/roguetown/serfs/alchemist.dm
  code/modules/jobs/job_types/roguetown/serfs/innkeep.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
  code/modules/mob/living/death.dm
  code/modules/paperwork/papers/scrap.dm
  code/modules/roguetown/roguemachine/ATM.dm
  config/config.txt
  config/motd.txt
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
  stonekeep.dme
  strings/books/law.json
  strings/rt/Lore_Primer.json
Labels: github

#31 I LOVE USA!
  _maps/vanderlin.dm
  code/__DEFINES/playerquality.dm
  code/__HELPERS/names.dm
  code/__HELPERS/roundend.dm
  code/_globalvars/configuration.dm
  code/_onclick/other_mobs.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/elastic.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/particle_weather.dm
  code/controllers/subsystem/particle_weather_outdoors.dm
  code/controllers/subsystem/plexora.dm
  code/controllers/subsystem/ticker.dm
  code/datums/components/storage/new_storage/tetris.dm
  code/datums/progressbar.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/game/objects/lighting/_base_roguelight.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/roguetown/redstone.dm
  code/game/objects/structures/walldeco.dm
  code/game/world.dm
  code/modules/admin/patreon.dm
  code/modules/antagonists/roguetown/villain/choosename.dm
  code/modules/antagonists/roguetown/villain/maniac/_maniac.dm
  code/modules/antagonists/roguetown/villain/peasantrebel.dm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/antagonists/roguetown/villain/zizocult.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelt.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelthand.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/rogue/creacher/familiar.dm
  code/modules/paperwork/rogue.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/roguetown/roguejobs/blacksmith/smelter.dm
  code/modules/roguetown/roguemachine/mail.dm
  code/modules/roguetown/roguemachine/steward.dm
  code/modules/roguetown/roguemachine/throne.dm
  code/world.dm
Labels: mapping

#32 Fixes werewolf speaking common
  _maps/map_files/vanderlin/vanderlin.dmm
  code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
Labels: mapping

#33 Removes PQ cause low pop
  code/__DEFINES/playerquality.dm
  code/modules/jobs/job_types/roguetown/adventurer/court_hand.dm
  code/modules/jobs/job_types/roguetown/apprentices/prince.dm
  code/modules/jobs/job_types/roguetown/church/inquisitor.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
  code/modules/jobs/job_types/roguetown/garrison/jailor.dm
  code/modules/jobs/job_types/roguetown/garrison/mayor.dm
  code/modules/jobs/job_types/roguetown/garrison/men_at_arms.dm
  code/modules/jobs/job_types/roguetown/garrison/royalguard.dm
  code/modules/jobs/job_types/roguetown/garrison/tollguard.dm
  code/modules/jobs/job_types/roguetown/garrison/tollkeeper.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/jobs/job_types/roguetown/nobility/archivist.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/consort.dm
  code/modules/jobs/job_types/roguetown/nobility/feldsher.dm
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/nobility/magician.dm
  code/modules/jobs/job_types/roguetown/nobility/merchant.dm
  code/modules/jobs/job_types/roguetown/nobility/minor_noble.dm
  code/modules/jobs/job_types/roguetown/nobility/nightman.dm
  code/modules/jobs/job_types/roguetown/nobility/steward.dm
  code/modules/jobs/job_types/roguetown/other/mercenary.dm
  code/modules/jobs/job_types/roguetown/peasants/butler.dm
  code/modules/jobs/job_types/roguetown/serfs/matron.dm
Labels: removal

#34 Map change, Make Elder into Old Woodcutter cause I like the name better
  _maps/map_files/vanderlin/vanderlin.dmm
  code/modules/jobs/job_types/roguetown/garrison/mayor.dm
Labels: mapping

#36 Re-names all mentions of Vanderlin to Eldermoor. Also Lich lair and phys hat
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  _maps/eldermoor.dm
  _maps/eldermoor.json
  _maps/map_files/eldermoor/eldermoor.dmm
  _maps/map_files/eldermoor/otherz/eldermoor_bog.dmm
  _maps/map_files/eldermoor/otherz/eldermoor_bog.json
  _maps/map_files/eldermoor/otherz/eldermoor_forest.dmm
  _maps/map_files/eldermoor/otherz/eldermoor_forest.json
  _maps/map_files/eldermoor/otherz/eldermoor_mountain.dmm
  _maps/map_files/eldermoor/otherz/eldermoor_mountain.json
  _maps/map_files/eldermoor/vanderlin_highpop.dmm
  _maps/map_files/eldermoor/who_is_working_on_what.txt
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/roguetown/otherz/smallforest.dmm
  _maps/map_files/vanderlin/otherz/vanderlin_bog.json
  _maps/map_files/vanderlin/otherz/vanderlin_forest.json
  _maps/map_files/vanderlin/who_is_working_on_what.txt
  code/__DEFINES/traits.dm
  code/_globalvars/lists/mapping.dm
  code/game/area/eldermoor/eldermoorareas.dm
  code/game/area/roguetownareas.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/game/objects/structures/traveltile.dm
  code/modules/antagonists/roguetown/villain/lich.dm
  code/modules/asset_cache/asset_cache_list.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/goonchat/browserassets/js/browserOutput.js
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/battlenun.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/physician.dm
  code/modules/jobs/job_types/roguetown/serfs/innkeep.dm
  code/modules/jobs/job_types/roguetown/serfs/physician.dm
  code/modules/jobs/job_types/roguetown/youngfolk/innkeepchild.dm
  code/modules/roguetown/mapgen/eldermoor/anvil.dm
  config/config.txt
  config/maps.txt
  icons/roguetown/clothing/onmob/head.dmi
  sound/music/credits.txt
  stonekeep.dme
  tools/ci/template_dm_generator.py
Labels: github

#37 re-enables elder as leader of outer town.
  _maps/map_files/eldermoor/eldermoor.dmm
  code/__DEFINES/jobs.dm
  code/_globalvars/lists/objects.dm
  code/game/gamemodes/roguetown/roguetown.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/jobs/job_types/roguetown/garrison/gatekeeper.dm
  code/modules/jobs/job_types/roguetown/garrison/mayor.dm
  code/modules/jobs/job_types/roguetown/serfs/matron.dm
  code/modules/jobs/jobs.dm
  stonekeep.dme
Labels: mapping
